package com.weilong.community.model;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbg.generated Thu Feb 17 10:43:32 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.parentid
     *
     * @mbg.generated Thu Feb 17 10:43:32 CST 2022
     */
    private Integer parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.type
     *
     * @mbg.generated Thu Feb 17 10:43:32 CST 2022
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commentauthor
     *
     * @mbg.generated Thu Feb 17 10:43:32 CST 2022
     */
    private Integer commentauthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.gmtcreate
     *
     * @mbg.generated Thu Feb 17 10:43:32 CST 2022
     */
    private Long gmtcreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.gmtmodify
     *
     * @mbg.generated Thu Feb 17 10:43:32 CST 2022
     */
    private Long gmtmodify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.likecount
     *
     * @mbg.generated Thu Feb 17 10:43:32 CST 2022
     */
    private Integer likecount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.content
     *
     * @mbg.generated Thu Feb 17 10:43:32 CST 2022
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commentcount
     *
     * @mbg.generated Thu Feb 17 10:43:32 CST 2022
     */
    private Integer commentcount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @mbg.generated Thu Feb 17 10:43:32 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @mbg.generated Thu Feb 17 10:43:32 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.parentid
     *
     * @return the value of comment.parentid
     *
     * @mbg.generated Thu Feb 17 10:43:32 CST 2022
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.parentid
     *
     * @param parentid the value for comment.parentid
     *
     * @mbg.generated Thu Feb 17 10:43:32 CST 2022
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.type
     *
     * @return the value of comment.type
     *
     * @mbg.generated Thu Feb 17 10:43:32 CST 2022
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.type
     *
     * @param type the value for comment.type
     *
     * @mbg.generated Thu Feb 17 10:43:32 CST 2022
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commentauthor
     *
     * @return the value of comment.commentauthor
     *
     * @mbg.generated Thu Feb 17 10:43:32 CST 2022
     */
    public Integer getCommentauthor() {
        return commentauthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commentauthor
     *
     * @param commentauthor the value for comment.commentauthor
     *
     * @mbg.generated Thu Feb 17 10:43:32 CST 2022
     */
    public void setCommentauthor(Integer commentauthor) {
        this.commentauthor = commentauthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.gmtcreate
     *
     * @return the value of comment.gmtcreate
     *
     * @mbg.generated Thu Feb 17 10:43:32 CST 2022
     */
    public Long getGmtcreate() {
        return gmtcreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.gmtcreate
     *
     * @param gmtcreate the value for comment.gmtcreate
     *
     * @mbg.generated Thu Feb 17 10:43:32 CST 2022
     */
    public void setGmtcreate(Long gmtcreate) {
        this.gmtcreate = gmtcreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.gmtmodify
     *
     * @return the value of comment.gmtmodify
     *
     * @mbg.generated Thu Feb 17 10:43:32 CST 2022
     */
    public Long getGmtmodify() {
        return gmtmodify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.gmtmodify
     *
     * @param gmtmodify the value for comment.gmtmodify
     *
     * @mbg.generated Thu Feb 17 10:43:32 CST 2022
     */
    public void setGmtmodify(Long gmtmodify) {
        this.gmtmodify = gmtmodify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.likecount
     *
     * @return the value of comment.likecount
     *
     * @mbg.generated Thu Feb 17 10:43:32 CST 2022
     */
    public Integer getLikecount() {
        return likecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.likecount
     *
     * @param likecount the value for comment.likecount
     *
     * @mbg.generated Thu Feb 17 10:43:32 CST 2022
     */
    public void setLikecount(Integer likecount) {
        this.likecount = likecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.content
     *
     * @return the value of comment.content
     *
     * @mbg.generated Thu Feb 17 10:43:32 CST 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.content
     *
     * @param content the value for comment.content
     *
     * @mbg.generated Thu Feb 17 10:43:32 CST 2022
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commentcount
     *
     * @return the value of comment.commentcount
     *
     * @mbg.generated Thu Feb 17 10:43:32 CST 2022
     */
    public Integer getCommentcount() {
        return commentcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commentcount
     *
     * @param commentcount the value for comment.commentcount
     *
     * @mbg.generated Thu Feb 17 10:43:32 CST 2022
     */
    public void setCommentcount(Integer commentcount) {
        this.commentcount = commentcount;
    }
}